name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: run-cmake
      uses: lukka/run-cmake@v2.5
      with:
          buildDirectory: ./build
    - name: run-tests
      run: ./runUnitTests
      working-directory: ./build
        
