name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: run-cmake
      uses: lukka/run-cmake@v2.5
      with:
          buildDirectory: '${{ runner.workspace }}/build'
    - name: run-tests
      run: make test
      working-directory: '${{ runner.workspace }}/build'
        
